services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: regs_user
      POSTGRES_PASSWORD: regs_password
      POSTGRES_DB: regs_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: